spring.application.name=api-gateway
##Las redirecciones de los microservicios se harán a través de este puerto:
server.port=8080
# WebFlux es el entorno por defecto para el Gateway Tradicional
# Inventory Service Routes:
spring.cloud.gateway.routes[0].id=inventory-mservices
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/inventory/**

# Order Service Routes:
spring.cloud.gateway.routes[1].id=orders-mservices
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

# Products Service Routes:
spring.cloud.gateway.routes[2].id=products-mservices
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/product/**