spring.application.name=api-gateway
##Las redirecciones de los microservicios se harán a través de este puerto:
server.port=9090
# Al tener server.port en los proyectos de microservicios, se generan puertos aleatorios que trabajan sobre el server y todo es renderizable desde el puerto 9090 ya que es el orquestador de las rutas y demás.


# EUREKA CLIENT
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

## LB prefijo que hace referencia a la carga balanceada:


# WebFlux es el entorno por defecto para el Gateway Tradicional
# Inventory Service Routes:
spring.cloud.gateway.server.webflux.routes[0].id=inventory-mservices
spring.cloud.gateway.server.webflux.routes[0].uri=lb://inventory-mservices
# http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/inventory/**

# Order Service Routes:
spring.cloud.gateway.server.webflux.routes[1].id=orders-mservices
spring.cloud.gateway.server.webflux.routes[1].uri=lb://orders-mservices
# http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**

# Products Service Routes:
spring.cloud.gateway.server.webflux.routes[2].id=products-mservices
spring.cloud.gateway.server.webflux.routes[2].uri=lb://products-mservices
# http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/product/**

#Discovery Server routes:
spring.cloud.gateway.routes[3].id=discovery-server
spring.cloud.gateway.routes[3].uri=http://localhost:8761
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[3].filters[0]=SetPath=/

#Discovery Server Static routes:
spring.cloud.gateway.routes[4].id=discovery-server-static
spring.cloud.gateway.routes[4].uri=http://localhost:8761
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/**



#Keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/microservices-realm

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.client-id=microservices_client
spring.security.oauth2.client.registration.keycloak.client-secret=q55jxIXmDqiaILfUBEl5svOCYuwBtM3I
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak


# Session y TokenRelay:
spring.cloud.gateway.default-filters[0]=SaveSession
spring.cloud.gateway.default-filters[1]=TokenRelay

# Flags para LOGS
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
# debug
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info