spring.application.name=inventory-mservices
server.port=0
# 8083

# EUREKA CLIENT
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/ms_inventory
spring.datasource.password=postgres
spring.datasource.username=postgres
